logging:
  level:
    root: INFO
    ru.vsu.cs: TRACE

spring.datasource:
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  url: jdbc:postgresql://localhost:5432/Agrin
  username: postgres
  password: root